#ifndef COMP_4985_PROTOCOL_TESTER_PROTOCOLCLIENTTESTS_H
#define COMP_4985_PROTOCOL_TESTER_PROTOCOLCLIENTTESTS_H

int testProtocolClient(void);

#endif    // COMP_4985_PROTOCOL_TESTER_PROTOCOLCLIENTTESTS_H
